### ISSUE TITLE
PDS 0301 ERROR CODE 0519

### ISSUE THREAD

**Issue by charisad** [adelosa/cardutil#11]
I keep getting this error from Mastercard, "FILE AMOUNT, CHECKSUM IS NOT ZEROES, AND DOES NOT EQUAL THE TOTAL OF AMOUNT, TRANSACTION (  00000000    P0301  DE4) FROM EACH DETAIL MESSAGE.", but the total amount tallies with the individual transaction amounts. Kindly assist. Attached is a zip file having the ipm and csv files.
[MCIPM_230428_00150_outgoing.zip](https://github.com/adelosa/cardutil/files/11381621/MCIPM_230428_00150_outgoing.zip)

**Comment by adelosa** [comment]
Just checking -- The title indicates an error

    PDS 0301 NOT INCLUDED IN FILE TRAILER (ERROR CODE 0519) 

This seems like a different error than what was provided in the body

    FILE AMOUNT, CHECKSUM IS NOT ZEROES, AND DOES NOT EQUAL THE TOTAL OF AMOUNT, TRANSACTION ( 00000000 P0301 DE4) FROM EACH DETAIL MESSAGE.

Was the 0519 error on the run without a value.. You need to provide a zero value for PDS301, not remove it completely.

**Comment by charisad** [comment]
> Just checking -- The title indicates an error
> 
> ```
> PDS 0301 NOT INCLUDED IN FILE TRAILER (ERROR CODE 0519) 
> ```
> 
> This seems like a different error than what was provided in the body
> 
> ```
> FILE AMOUNT, CHECKSUM IS NOT ZEROES, AND DOES NOT EQUAL THE TOTAL OF AMOUNT, TRANSACTION ( 00000000 P0301 DE4) FROM EACH DETAIL MESSAGE.
> ```
> 
> Was the 0519 error on the run without a value.. You need to provide a zero value for PDS301, not remove it completely.

the error code is 0519 - FILE AMOUNT, CHECKSUM IS NOT ZEROES, AND DOES NOT EQUAL THE TOTAL OF AMOUNT, TRANSACTION ( 00000000 P0301 DE4) FROM EACH DETAIL MESSAGE.

**Comment by adelosa** [comment]
Thanks for confirming.

**Comment by adelosa** [comment]
Have you resolved your issue?

**Comment by charisad** [comment]
> Have you resolved your issue?

Hi Anthony, I received the reconciliation file today, the issue has been resolved after making all the PDS 0301 Data field zeros.
