### ISSUE TITLE
Dropping Zero Byte Length PDS Fields

### ISSUE THREAD

**Issue by kirk-daries** [adelosa/cardutil#13]
Hi there,

We are busy using the Mastercard Clearing Simulator as part of the clearing certification and one of the warnings we keep seeing is that certain records are flagged as 'invalid' because we did not specify any data in them.

i.e. PDS0184 is not present for Moto transactions.
However other records contains this field.. so we can't 'drop' the usage completely (3DS records).

Is this a bug/incorrect usage on our side? or something we can improve upon on cardUtil?

Thanks

**Comment by adelosa** [comment]
I assume you are generating an IPM file from a csv. And the PDS field is present in the csv file but some records don't need this PDS value. Is Cardutil adding the pds field with no value?

**Comment by kirk-daries** [comment]
Apologies, I should have given you more context.
I am indeed calling the `mci_csv_to_ipm` utility. 

The csv file contains headers for the PDS fields but certain cells for some rows are 'empty' / not populated.

And yes, from the output i'm seeing on the Clearing Simulator, it appears as if the fields are always added but the length value is zero.

**Comment by kirk-daries** [comment]
![cardUtil zero length warning](https://github.com/adelosa/cardutil/assets/19187979/18bcc496-1a65-456d-9af6-e959d7b82b63)

Feedback from the Simulator we are seeing.
I'm unsure if this is purely a Simulator problem only at this point. I've reached out on mastercard end for comment.

**Comment by kirk-daries** [comment]
Feedback from Mastercard. 

![image](https://github.com/adelosa/cardutil/assets/19187979/5e772ed8-eb4e-4f1f-8a73-212527654b93)

Can you confirm this is indeed a problem currently? Or is there something i can do on the CSV generation side?

**Comment by adelosa** [comment]
This should be fairly easy to fix so that if a field is empty, it is dropped from the message and avoids this error.

**Comment by adelosa** [comment]
I have just pushed v0.6.3 which have updated CSV to IPM tool to remove blank PDS fields from the IPM file.
Let me know if this resolves your issue.

**Comment by kirk-daries** [comment]
Confirmed! This is now resolved! Thank you very much @adelosa !
