### ISSUE TITLE
Invalid record length - value read was 805306492

### ISSUE THREAD

**Issue by mrtemp2** [adelosa/cardutil#17]
hi i have a IPM mastercard file and i'm trying to get the transaction or whatever information maybe in it iv tried to convert it using the command mci_ipm_to_csv i always get this error 

` mci_ipm_to_csv --debug file.IPM --in-encoding CP500
mci_ipm_to_csv (cardutil 0.6.4)
parameters:
 -in_filename:file.IPM
 -in_encoding:CP500
 -debug:True
DEBUG:cardutil.cli:config_dir=None
DEBUG:cardutil.mciipm:record_length=805306492
*** ERROR - processing has stopped ***
Error detected in record 1
Invalid record length - value read was 805306492
`

[fileIPM.txt](https://github.com/adelosa/cardutil/files/14259752/fileIPM.txt)

**Comment by adelosa** [comment]
If the first record has an invalid record length then the file is not valid. 
The first 4 bytes should contain the length of the record in binary.

**Comment by mrtemp2** [comment]
Good morning but the file that is attached is from mastercard and i suppose it have the structure required to be extracted with the command mci_ipm_to_csv

**Comment by adelosa** [comment]
Closing as the file is not in IPM format

**Comment by adelosa** [comment]
It appears that this file is using the Mastercard Clearing Optimiser AutoEdit input file structure. 
When I reviewed the file, it does have valid IPM records embedded within the structure with some additional file and record headers. I am not sure how these files are used and when you would use these in preference to a standard IPM file.
The bottom line is that cardutils does not support this format. I will leave this here as a "TODO" to see if there is 
any interest in supporting this format.
