### ISSUE TITLE
mci_ipm_encode : FAILED to ENCODE ASCII into EBCDIC File format

### ISSUE THREAD

**Issue by ChristopheVastesaeger** [adelosa/cardutil#4]
When using the mci_ipm_encode tool to encode ascii file into EBCDIC format get following error :
**UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)**

options used : --in-encoding ascii --out-encoding cp500

**Anybody idea how to solve this issue ?**

quote
    return _iso8583_to_dict(b, iso_config, encoding, hex_bitmap)
  File "c:\users\vastesaeger\appdata\local\programs\python\python39\lib\site-packages\cardutil\iso8583.py", line 170, in _iso8583_to_dict
    return_values["MTI"] = message_type_indicator.decode(encoding)
**UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)**
unquote

**Comment by adelosa** [comment]
Hi there,
In general, if you are just converting an "Ascii" file, I would advise that you instead use the Latin1 encoding which is the default.
Strict ASCII as implemented in python will complain about any char coded above 128.. that may be what you want but unlikely.
So try rerunning with just `--out-encoding cp500` or with `--in-encoding latin1 --out-encoding cp500` if you want to be explicit.
Let me know how you go.

**Comment by ChristopheVastesaeger** [comment]
THANKS FOR YOUR INFORMATION VERY USEFULL, I'M STEP FUTHER and i think i miss in the config.py couple of entries in bit_config. Is there anybody who has a full bit_config table?
   "bit_config": {
        "1": {"field_name": "Bitmap secondary", "field_type": "FIXED", "field_length": 8},
        "2": {"field_name": "PAN", "field_type": "LLVAR", "field_length": 0},  # "field_processor": "PAN"},
        "3": {"field_name": "Processing code", "field_type": "FIXED", "field_length": 6},
        "4": {"field_name": "Amount transaction", "field_type": "FIXED", "field_length": 12,
              "field_python_type": "long"},
        "5": {"field_name": "Amount, Reconciliation", "field_type": "FIXED", "field_length": 12,
              "field_python_type": "long"},
        "6": {"field_name": "Amount, Cardholder billing", "field_type": "FIXED", "field_length": 12,
              "field_python_type": "long"},
        "9": {"field_name": "Conversion rate, Reconciliation", "field_type": "FIXED", "field_length": 8,
              "field_python_type": "long"},
.......

**Comment by adelosa** [comment]
I believe it's a full config for MasterCard so if you are still missing config it could be another issue. The default config has been used in production systems for a few years now without issue.

**Comment by adelosa** [comment]
Please let me know if you have resolved the issue.
