### ISSUE TITLE
First presentment missing DE43. mci_csv_to_ipm

### ISSUE THREAD

**Issue by charisad** [adelosa/cardutil#6]
After creating a file from csv using mci_csv_to_ipm, The ipm file is missing DE43, with this I mean the space occupied by DE43 in the file is blank. Kindly advise.

**Comment by adelosa** [comment]
Please provide example CSV that causes the issue so I can investigate.

**Comment by charisad** [comment]
> Please provide example CSV that causes the issue so I can investigate.
[MCCreditAcq_20220612175118667_outgoing.csv](https://github.com/adelosa/cardutil/files/8888311/MCCreditAcq_20220612175118667_outgoing.csv)
Please find attached Sample csv

**Comment by adelosa** [comment]
Provide just a DE43 field and do not use the DE43 subfields in your CSV.

**Comment by charisad** [comment]
> Provide just a DE43 field and do not use the DE43 subfields in your CSV.

Done I have it working. Thanks
