### ISSUE TITLE
Issue reading IPM Parameter File in ASCII Format

### ISSUE THREAD

**Issue by Shailesh2276** [adelosa/cardutil#9]
Hello Adelosa,
Need small help. I have already IPM parameter file converted by MasterCard in ASCII format but unable to read through cardutil.  
file format extension is ".PMF"
mci_ipm_param_to_csv process is taking long time but still it is not able to read the file.

Regards,
Shailesh

**Comment by adelosa** [comment]
Please attach example file you are trying to process along with any details from Mastercard specifications and document details.
